ci: debos: Update OS packages first
During some GitHub workflow runs, incus exec commands are randomly
interrupted by:
    Error: websocket: close 1006 (abnormal closure): unexpected EOF

It's possible that this is due to an OS update happening during the run,
so pre-emptively do the updates first, which is a good idea for bug
fixes and predicatibility anyway.

Signed-off-by: Loïc Minier <loic.minier@oss.qualcomm.com>